### PR TITLE
documentation and licencing changes

### PR DESCRIPTION
**Pull request by angleto**
- used GPLv2 instead of GPLv3
- added a new default logging level
- update software dependency in build.sbt
- simplified a step in documentation

### CODE REVIEW

**Comment by shlomizadok** [comment]
@angleto - why do you changes to GPLV2?
Also, if you do, maybe also change the `LICENSE` file?

**Comment by angleto** [comment]
@shlomizadok the GPLv3 introduce some restriction which could make the applicability a bit more complicated. We are evaluating the implication of the application of both licenses in order to decide which one to apply.

**Comment by shlomizadok** [comment]
@angleto - Squash into one commit? LGTM anyhow :)

**Comment by angleto** [comment]
thanks @shlomizadok let's wait for Mario's opinion before the merge.

**Pull request merged**
